#!/bin/bash 
# probably no posix :(

# DO NOT edit this file directory (except in cases where you want to

#container_image="debian:12"
#hostname="debiandeclarative"
#username="debianuser"
#apt_packages="vim neofetch zsh"

echo $apt_packages # debug
echo $chroot_directory

main(){
	podman_pull_bootstrap
}

# added EXPLICIT HARDCODED `-v` flag (contrast with ${v_key} variable
podman_pull_bootstrap(){
	podman pull ${container_image} && podman save ${container_image} | tar -xpf - -O | tar -v -xpf - -C ${chroot_directory}
}

# TODO: dynamic distro version string
add_apt_repositories(){
	chroot ${chroot_dir} << EOS
cat > /etc/apt/sources.list << EOT
deb http://deb.debian.org/debian bookworm main non-free-firmware
EOT
	apt-get update
EOS

}

apt_install_systemd(){
	chroot ${chroot_directory} << EOS
apt-get install -y systemd
EOS
}

set_hostname(){
	chroot ${chroot_directory} << EOS
hostnamectl hostname ${hostname}
EOS
}

apt_packages(){
	chroot ${chroot_directory} << EOS
apt-get install -y \
bash \
systemd \
linux-image \
coreutils

EOS
}

main
apt_install_systemd
set_hostname
apt_packages
