#!/bin/bash 

set -o posix

# DO NOT edit this file directory (except in cases where you want to fix it)

#export container_image="debian:12"
#export hostname="debiandeclarative"
#export username="debianuser"
#export apt_packages="vim neofetch zsh"
#
#export project_directory="./" # (dirty hack) TODO: replace it
#
#export chroot_directory="$1" # do not access $1 ever again


echo $apt_packages # debug
echo $chroot_directory # debug

project_mount="/opt/project/"

#build_root="/tmp/iso-$(date +%d%m%Y)-$(tr -dc a-z </dev/urandom | head -c 4)" # disabled for now

container_name="bootstrap-$(tr -dc a-z </dev/urandom | head -c 4)"

# to be replaced with containerfile
#podman run --rm --name ${container_name} --volume ${project_directory}:${project_mount}:z -it ${container_image} /bin/bash
podman run --name ${container_name} --volume ${project_directory}:${project_mount}:z -it ${container_image} /bin/bash

# beware -- using the same string for the latter container image
podman commit ${container_name} ${container_name}

podman save ${container_image} | tar ${overwrite_key} -xpf - -O | tar -v ${overwrite_key} -xpf - -C ${chroot_directory} # no cleanup? kek 

podman image rm ${container_name}
